name: Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.4.2']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Check Gemfile.lock consistency
      run: |
        bundle check || (echo "Gemfile.lock is out of sync with Gemfile. Please update it." && exit 1)

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Run Brakeman
      run: bundle exec brakeman

    - name: Run Bundler Audit
      run: bundle exec bundler-audit check --update

    - name: Run Tests
      run: bundle exec rspec

    - name: Run RSpec with coverage
      env:
        SIMPLECOV: true
      run: bundle exec rspec

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
