name: Push Gem

on:
  workflow_run:
    workflows: ["Code Quality"]
    types:
      - completed

jobs:
  publish:
    name: Build and Publish Gem
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.2
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Install oathtool
      run: sudo apt-get install -y oathtool

    - name: Check if version exists on RubyGems
      id: check_version
      run: |
        gem build *.gemspec
        gem_name=$(ls *.gem | head -n 1)
        gem_version=$(echo $gem_name | grep -oP '\d+\.\d+\.\d+')
        gem_name_without_version=$(basename $gem_name .gem)
        if gem search "^${gem_name_without_version}$" --remote | grep -q $gem_version; then
          echo "Version $gem_version already exists on RubyGems. Skipping publish."
          echo "version_exists=true" >> $GITHUB_ENV
        else
          echo "version_exists=false" >> $GITHUB_ENV
        fi

    - name: Publish to RubyGems
      if: env.version_exists == 'false'
      run: |
        echo "Ensure MFA is enabled on your RubyGems account (UI and API level)."
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_AUTH_TOKEN}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        otp=$(oathtool --totp -b "${RUBYGEMS_OTP_SECRET}")
        gem push *.gem --otp ${otp}
      env:
        RUBYGEMS_AUTH_TOKEN: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
        RUBYGEMS_OTP_SECRET: ${{ secrets.RUBYGEMS_OTP_SECRET }}
